[params.hugopress.modules.hb-blog-toc-scrollspy.attributes.hb-blog-post-content]
cacheable = true

[[module.imports]]
path = "github.com/hbstack/toc-scrollspy"

[[module.imports]]
path = "github.com/hbstack/blog"
