[[module.imports]]
path = "github.com/hugomods/twikoo"

[[module.imports]]
path = "github.com/hbstack/blog"

[params.hugopress.modules.hb-blog-comments-twikoo.hooks.hb-blog-post-comments]

[params.hugopress.modules.hb-blog-comments-twikoo.hooks.body-end]
