[[module.imports]]
path = "github.com/hbstack/blog"

[[module.imports]]
path = "github.com/hbstack/slide"

[params.hugopress.modules.hb-blog-related-posts.hooks.hb-blog-post-content-end]

[params.hb.blog.related_posts]
number = 10
