[[module.imports]]
path = "github.com/hbstack/blog"

[params.hugopress.modules.hb-blog-post-authors.hooks.hb-blog-post-content-begin]

[params.hugopress.modules.hb-blog-post-authors.hooks.hb-blog-post-content-end]

[params.hb.blog.post_authors]
position = "top"
