[[module.imports]]
path = "github.com/hbstack/blog"

[[module.imports]]
path = "github.com/hbstack/content-panel"

[params.hugopress.modules.hb-blog-post-content-panel.hooks.hb-blog-post-content-end]
